# Generated by Django 4.0.6 on 2022-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(default='1999-12-26'),
            preserve_default=False,
        ),
    ]
