# Generated by Django 4.0.6 on 2022-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_user_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='nombre',
            field=models.CharField(default='herramienta', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meta',
            name='nombre',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='nombre',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
    ]
