# Generated by Django 4.0.6 on 2022-08-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0003_herramienta_nombre_meta_nombre_plan_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_usuario',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
